// Type-based color mapping

export const typeColors: Record<string, string> = {
  normal: 'bg-gray-400',
  fire: 'bg-red-500',
  water: 'bg-blue-500',
  electric: 'bg-yellow-400',
  grass: 'bg-green-500',
  ice: 'bg-blue-200',
  fighting: 'bg-red-700',
  poison: 'bg-purple-600',
  ground: 'bg-yellow-600',
  flying: 'bg-indigo-300',
  psychic: 'bg-pink-500',
  bug: 'bg-lime-500',
  rock: 'bg-yellow-800',
  ghost: 'bg-purple-800',
  dragon: 'bg-indigo-700',
  dark: 'bg-gray-800',
  steel: 'bg-gray-500',
  fairy: 'bg-pink-300',
};

export const typeBorderColors: Record<string, string> = {
  normal: 'border-gray-400',
  fire: 'border-red-500',
  water: 'border-blue-500',
  electric: 'border-yellow-400',
  grass: 'border-green-500',
  ice: 'border-blue-200',
  fighting: 'border-red-700',
  poison: 'border-purple-600',
  ground: 'border-yellow-600',
  flying: 'border-indigo-300',
  psychic: 'border-pink-500',
  bug: 'border-lime-500',
  rock: 'border-yellow-800',
  ghost: 'border-purple-800',
  dragon: 'border-indigo-700',
  dark: 'border-gray-800',
  steel: 'border-gray-500',
  fairy: 'border-pink-300',
};

export const typeTextColors: Record<string, string> = {
  normal: 'text-gray-700',
  fire: 'text-red-700',
  water: 'text-blue-700',
  electric: 'text-yellow-700',
  grass: 'text-green-700',
  ice: 'text-blue-400',
  fighting: 'text-red-800',
  poison: 'text-purple-700',
  ground: 'text-yellow-800',
  flying: 'text-indigo-500',
  psychic: 'text-pink-700',
  bug: 'text-lime-700',
  rock: 'text-yellow-900',
  ghost: 'text-purple-900',
  dragon: 'text-indigo-800',
  dark: 'text-gray-900',
  steel: 'text-gray-600',
  fairy: 'text-pink-500',
};